networks:
  app-network:
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sh -c "wait && npm run dev"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/tsoa.json:/app/tsoa.json
      - ./backend/jest.config.ts:/app/jest.config.ts
    environment:
      PORT: 8004
      CONNECTION_STRING: mongodb://mongodb:27019/package-tracker
      JWT_SECRET: 'this-may-change'
    ports:
      - 8004:8004
    stdin_open: true
    tty: true
    depends_on:
      - database
    networks:
      - app-network

  web-client:
    container_name: web-client
    build:
      context: ./web-client
      dockerfile: Dockerfile
    command: sh -c "ng serve --host 0.0.0.0 --port 4200"
    ports:
      - '4200:4200'
    volumes:
      - ./web-client/src:/app/src
    environment:
      - STYLE=css
    networks:
      - app-network

  web-driver:
    container_name: web-driver
    build:
      context: ./web-driver
      dockerfile: Dockerfile
    command: sh -c "ng serve --host 0.0.0.0 --port 4201"
    ports:
      - '4201:4201'
    volumes:
      - ./web-driver/src:/app/src
    environment:
      - STYLE=css
    networks:
      - app-network

  web-admin:
    container_name: web-admin
    build:
      context: ./web-admin
      dockerfile: Dockerfile
    command: sh -c "ng serve --host 0.0.0.0 --port 4202"
    ports:
      - '4202:4202'
    volumes:
      - ./web-admin/src:/app/src
    environment:
      - STYLE=css
    networks:
      - app-network

  # mongodb service
  database:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - '27019:27019'
    volumes:
      - ./database:/database/
      - ./mongod.conf:/etc/mongod.conf
    command: mongod --config /etc/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: # DATABASE_NAME
      MONGO_INITDB_ROOT_PASSWORD: # DATABASE_USER
    networks:
      - app-network
